NetworkExpansion: 1
TimeDomainReductionFolder: "TDR_Results"
ParameterScale: 1
EnergyShareRequirement: 0
PrintModel: 0
TimeDomainReduction: 1
Trans_Loss_Segments: 1
CapacityReserveMargin: 0
ModelingtoGenerateAlternativeSlack: 0.1
Solver: "Gurobi"
MultiPeriodSettingsDict:
  ConvergenceTolerance: 0.01
  NumPeriods: 3
  PeriodLength: 10
  WACC: 0.045
  CurPeriod: 3
LongDurationStorage: 0
Reserves: 0
StorageLosses: 1
OperationWrapping: 1
OverwriteResults: 0
UCommit: 0
ModelingToGenerateAlternatives: 0
MinCapReq: 0
CO2Cap: 2
WriteShadowPrices: 0
MultiPeriod: 1
