# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - 1.7
  - 1.8
  - 1.9
branches:
  only:
    - main
    - gh-pages
os:
  - linux
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  include:
    - stage: Documentation
      julia: 1.6
      script: |
        julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: DocMeta, doctest
          using GenX
          DocMeta.setdocmeta!(GenX, :DocTestSetup, :(using GenX); recursive=true)
          doctest(GenX)
          include("docs/make.jl")'
      after_success: skip
