name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Bug description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Environment and Version
      description: |
        What are your OS, Julia version, and GenX version (release/tag, branch, or commit)?
      placeholder: MacOS, Julia 1.x, main branch v0.x.y
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant error messages
      description: Please copy and paste any relevant error messages output. This will be automatically formatted into code, so no need for backticks. (optional)
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Anything else that would help us understand or fix this (optional)
