NumPeriods: 3 # Number of model periods
PeriodLengths: [10,10,10] # Length of each model period (years)
WACC: 0.045 # Weighted average cost of capital
ConvergenceTolerance: 0.01 # Relative optimality gap used for convergence